from __future__ import annotations

import operator
from typing import Annotated, Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field
from typing_extensions import TypedDict


# --- Pydantic Data Models (Structured Data & Validation) ---

class SummaryCards(BaseModel):
    """Compact five-card summary shown before the full PMRL disclosure."""

    tldr: str = Field(default="", description="One or two sentences stating the contribution and conclusion.")
    problem: str = Field(default="", description="The specific problem addressed, in 30-60 words.")
    method: str = Field(default="", description="The core mechanism, in 30-60 words.")
    key_results: str = Field(default="", description="One to three source-backed findings, in 30-60 words.")
    why_it_matters: str = Field(default="", description="A concise implication distinct from measured results, in 30-60 words.")


class PMRLGeneration(BaseModel):
    """Provider schema for the detailed PMRL call.

    Compact Results cards are intentionally absent: they are generated after
    the report is synthesized, using the report plus source evidence.
    """

    problem: str = Field(description="Core problem, scientific background, challenges, and baseline limitations.")
    method: str = Field(description="Proposed methodology, key architectural designs, algorithms, formulas.")
    result: str = Field(description="Key empirical results, benchmark datasets, evaluation metrics, SOTA gains.")
    limitation: str = Field(description="Limitations, trade-offs, theoretical assumptions, and future work directions.")
    brief_summary: str = Field(
        default="",
        description="Legacy compact conclusion plus 3 or 4 bullets, at most 150 words; empty when unavailable.",
    )


class PMRLNotes(BaseModel):
    """Structured research paper notes following the PMRL framework."""
    problem: str = Field(
        description="Core problem, scientific background, challenges, and baseline limitations."
    )
    method: str = Field(
        description="Proposed methodology, key architectural designs, algorithms, formulas."
    )
    result: str = Field(
        description="Key empirical results, benchmark datasets, evaluation metrics, SOTA gains."
    )
    limitation: str = Field(
        description="Limitations, trade-offs, theoretical assumptions, and future work directions."
    )
    # Result cards shown in the default Results summary.  They are populated
    # by the post-report summary step and remain separate from full PMRL text.
    summary_cards: SummaryCards = Field(default_factory=SummaryCards)
    # Set by local validation after the provider response.  It is metadata for
    # the API and is not a claim generated by the model.
    summary_quality: Literal["complete", "invalid", "missing", "unknown"] = "unknown"
    # Legacy compact field retained for old runs. New Results cards use
    # ``summary_cards`` and this field is not synthesized from PMRL prose.
    brief_summary: str = Field(
        default="",
        description=(
            "One-sentence conclusion followed by exactly 3 or 4 concise bullet "
            "points, at most 150 words in total."
        ),
    )


class ComparisonMetric(BaseModel):
    """One metric claim with explicit comparability evidence."""

    metric: str = ""
    dataset: str = ""
    unit: str = ""
    value: str = ""
    source_quote: str = ""


class ComparisonPaper(BaseModel):
    """Short per-paper findings used by the comparison artifact."""

    paper_id: str = ""
    title: str = ""
    findings: List[str] = Field(default_factory=list)
    metrics: List[ComparisonMetric] = Field(default_factory=list)


class ComparisonRow(BaseModel):
    """A comparison row validated against each paper's source text."""

    metric: str = ""
    dataset: str = ""
    unit: str = ""
    values: Dict[str, str] = Field(default_factory=dict)
    source_quotes: Dict[str, str] = Field(default_factory=dict)
    comparable: bool = False
    reason: str = ""


class ComparisonArtifact(BaseModel):
    """Structured comparison returned by the single benchmark LLM call."""

    papers: List[ComparisonPaper] = Field(default_factory=list)
    rows: List[ComparisonRow] = Field(default_factory=list)
    synthesis: List[str] = Field(default_factory=list)


class GitHubRepoInfo(BaseModel):
    """Metadata for an open-source repository matching a paper."""
    name: str
    url: str
    stars: int = 0
    framework: str = "Python"
    is_official: bool = False
    description: str = ""


class PaperItem(BaseModel):
    """Data model representing an academic paper across the lifecycle."""
    paper_id: str                          # Canonical key (e.g. arxiv_2312.00752 or local_hash)
    title: str
    summary: str = ""
    authors: List[str] = Field(default_factory=list)
    published: str = ""
    subjects: List[str] = Field(default_factory=list)
    source_type: Literal["arxiv", "local_pdf"] = "arxiv"
    arxiv_id: Optional[str] = None
    arxiv_abs_url: Optional[str] = None
    arxiv_html_url: Optional[str] = None
    pdf_url: Optional[str] = None
    local_pdf_path: Optional[str] = None
    # Metadata comes from the versioned ArXiv API record.  ``unknown`` means
    # no trustworthy record was available; ``missing`` means a record was
    # returned but one or more display fields were absent.
    metadata_status: Literal["complete", "missing", "unknown"] = "unknown"
    
    # Text Extraction
    extracted_text: Optional[str] = None    # Raw full text excerpts
    sections: Dict[str, str] = Field(default_factory=dict) # {"abstract": "...", "methodology": "...", "experiments": "...", "limitations": "..."}
    
    # Enrichment
    github_repos: List[GitHubRepoInfo] = Field(default_factory=list)
    bibtex: Optional[str] = None
    
    # PMRL Notes
    notes: Optional[PMRLNotes] = None
    # Measured source and extraction quality.  These values are safe metadata;
    # raw extracted text and section bodies remain internal workflow state.
    source_quality: Dict[str, Any] = Field(default_factory=dict)
    notes_quality: Literal["complete", "invalid", "missing", "unknown"] = "unknown"
    # Internal timing metadata collected by tools/nodes.  API DTOs should
    # expose only allow-listed numeric measurements from this map.
    processing_metadata: Dict[str, Any] = Field(default_factory=dict)


class EvalSearchOutput(BaseModel):
    """Structured evaluation output for search quality assessment."""
    passed: bool = Field(description="True if papers are highly relevant to query; False otherwise.")
    score: float = Field(description="Relevance score from 0.0 to 1.0.")
    feedback: str = Field(description="Critique explaining why query passed or needs refinement.")
    selected_indices: List[int] = Field(
        default_factory=list,
        description="0-based indices of the best papers to select for deep reading."
    )


# --- Global LangGraph State (TypedDict with Reducers) ---

class ResearchState(TypedDict):
    """Global state flowing through the LangGraph workflow."""
    # Inputs
    user_query: str                          # Research topic or question
    raw_inputs: List[str]                    # URLs, ArXiv IDs, or local PDF paths
    
    # Router & Execution Flow
    intent: Literal["direct_answer", "direct_read", "search", "direct_compare"]
    status: Literal["running", "success", "degraded", "error"]
    error_message: Optional[str]

    # Compact context supplied by the API for a follow-up question.  This is
    # deliberately separate from the internal paper text/cache fields so the
    # answer node can be constrained to safe, already-produced artifacts.
    conversation_context: str
    
    # Search & Evaluation
    search_query: str
    search_results: List[PaperItem]
    retry_count: int
    eval_passed: bool
    eval_feedback: str
    
    # Selected Papers for Deep Reading
    selected_papers: List[PaperItem]
    
    # Output Synthesis
    benchmark_matrix: Optional[str]          # Markdown benchmark comparison table
    comparison_artifact: Optional[Dict[str, Any]]  # Structured comparison for Results UI
    final_report: Optional[str]              # Comprehensive research report (Markdown)
    assistant_answer: str                    # Direct/follow-up answer (not a report)

    # Append-only measured timings.  Each node writes its own key, preserving
    # the existing LangGraph topology while making timing visible to API
    # consumers without recording prompts, paper text, or credentials.
    node_timings: Annotated[Dict[str, Dict[str, Any]], operator.or_]
    
    # Observability & Tracing (Annotated Reducers to append logs without overwriting)
    trace_logs: Annotated[List[str], operator.add]
    error_logs: Annotated[List[str], operator.add]
